name:
  Intégration continue du projet

# Quand cette action sera déclenchée ?
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Tâches ("jobs") à accomplir
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php
          php --version

      - name: Installation de PHPUnit
        run: |
          wget https://phar.phpunit.de/phpunit.phar
          chmod +x phpunit.phar
          sudo mv phpunit.phar /usr/local/bin/phpunit

      - name: Exécution des tests PHPUnit
        run: |
          cd tests
          phpunit --list-tests .