name:
  CI

# Quand cette action sera déclenchée ?
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

# Tâches ("jobs") à accomplir
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialisation de PHP 8.1.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit
          extensions: mbstring, PDO, grpc, tokenizer, xml, json, ctype, fileinfo, openssl, bcmath

      - name: Exécution de PHPUnit
        run: phpunit ${GITHUB_WORKSPACE}/tests/